### ISSUE TITLE
deep link to a callgraph line

### ISSUE THREAD

**Issue by mapsam** [mapsam/callgraph#3]
It'd be great to deep link to a callgraph line, which will require expanding the lists to the proper spot.

**Comment by springmeyer** [comment]
❤️

**Comment by mapsam** [comment]
Resolved in https://github.com/mapsam/callgraph/commit/b690bb35a4627764d0e23707320cfb5ff79a3b68

![callgraph-deeplink](https://user-images.githubusercontent.com/1943001/32984752-548479d2-cc61-11e7-96b8-7b6561ced7ae.gif)
